version: '3'
services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lumen_articles_app
    volumes:
      - ./storage:/var/www/storage
    env_file: '.env'
    environment:
      - "DB_HOST=database"

  #Web Server
  web:
    container_name: nginx_server
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8990:80"
    volumes:
      - ./storage/logs/:/var/log/nginx

  #Database
  database:
    image: mysql:5.7
    container_name: mysql_database
    ports:
      - "8991:3306"
    environment:
      MYSQL_DATABASE: articulate
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql

#Docker Networks
networks:
  app-network:
    driver: bridge

#Named Volumes
volumes:
    dbdata: